[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200
force = false

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200
force = false

[[headers]]
for = "/robots.txt"

[headers.values]
Content-Type = "text/plain"

[[headers]]
for = "/sitemap.xml"

[headers.values]
Content-Type = "application/xml"

[[headers]]
for = "/*"

[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://images.pexels.com https://www.google.com https://www.googletagmanager.com https://www.google-analytics.com https://unpkg.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://images.pexels.com https://www.google-analytics.com https://media.istockphoto.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://formsubmit.co; frame-src https://www.google.com https://www.google.com/maps/;"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/img/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/pdfs/*"

[headers.values]
Content-Type = "application/pdf"
Cache-Control = "public, max-age=86400"

[build]
command = "npx vite build"
publish = "dist"